# Generated by Django 4.0.1 on 2022-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('middlename', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('degree', models.CharField(max_length=12)),
                ('semester', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=122)),
                ('photo', models.FileField(upload_to='')),
                ('signature', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
