# Generated by Django 4.0.1 on 2022-01-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_registration_alter_login_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='passwrd',
        ),
    ]
