# Generated by Django 4.0.1 on 2022-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_rename_password_registration_passwrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='firstname',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
