# Generated by Django 4.0.1 on 2022-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_alter_registration_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='degree',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
