# Generated by Django 4.0.1 on 2022-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_alter_registration_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lastname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='middlename',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='passwrd',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pincode',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='semester',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
